To Do List Application/Models/ErrorViewModel.cs
using System;

namespace To_Do_List_Application.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

To Do List Application/Controllers/HomeController.cs
using domain_entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using To_Do_List_Application.Models;

namespace To_Do_List_Application.Controllers
{

    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ToDoDbContext _db;

        public HomeController(ILogger<HomeController> logger, ToDoDbContext db)
        {
            _logger = logger;
            _db = db;
        }
        public ActionResult Index()
        {
            var results = _db.ToDoList.ToList();
            return View(results);
        }

        [Route("create")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("create")]
        public ActionResult Create(ToDoList list)
        {
            _db.Add(list);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Route("delete")]
        public ActionResult Delete(int id)
        {
            var item = _db.ToDoList.Where(x => x.Id == id).FirstOrDefault();
            return View(item);
        }

        [HttpPost]
        [Route("delete")]
        public ActionResult Delete(ToDoList list)
        {
            _db.ToDoList.Remove(list);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

To Do List Application/Controllers/ToDoController.cs
using domain_entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace To_Do_List_Application.Controllers
{
    [Route("todo")]
    public class ToDoController : Controller
    {
        private readonly ToDoDbContext _db;

        public ToDoController(ToDoDbContext db)
        {
            _db = db;
        }

        public ToDoController()
        {
        }

        public ActionResult Index()
        {
            var results = _db.ToDoList.ToList();
            return View(results);
        }

        /*[Route("create")]
        public ActionResult Create()
        {
            return View();
        }*/

        //[HttpPost]
        [Route("create")]
        public IActionResult Create(ToDoList list)
        {
            _db.ToDoList.Add(list);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Route("list")]
        public IActionResult List()
        {
            var results = _db.ToDoList.ToList();
            return View(results);
        }

        [Route("delete")]
        public ActionResult Delete(int id)
        {
            var item = _db.ToDoList.Where(x => x.Id == id).FirstOrDefault();
            return View(item);
        }
    }
}

To Do List Application/Controllers/ToDoitemsController.cs
using domain_entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace To_Do_List_Application.Controllers
{
    [Route("todoitems")]
    public class ToDoitemsController : Controller
    {
        private readonly ToDoDbContext db;
        private readonly ToDoItemsDbContext dbItems;

        public ToDoitemsController(ToDoDbContext db, ToDoItemsDbContext dbItems)
        {
            this.db = db;
            this.dbItems = dbItems;
        }

        [HttpGet]
        [Route("")]
        public ActionResult Index(ToDoList list)
        {
            var items = dbItems.ToDoItem;
            List<ToDoItems> res = new List<ToDoItems>();

            res = dbItems.ToDoItem.Where(x => x.ListName == list.Name).ToList();

            return View(res);
        }

        [Route("create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("create")]
        public ActionResult Create(ToDoItems item)
        {
            dbItems.Add(item);
            dbItems.SaveChanges();
            return Redirect("/home");
        }

        [Route("edit")]
        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        [Route("edit")]
        public ActionResult Edit(ToDoItems item)
        {
            dbItems.Update(item);
            dbItems.SaveChanges();
            return Redirect("/home");
        }

        [Route("delete")]
        public ActionResult Delete(int id)
        {
            var item = dbItems.ToDoItem.Where(x => x.Id == id).FirstOrDefault();
            return View(item);
        }

        [Route("deleteconfirm")]
        public ActionResult DeleteConfirm(int id)
        {
            var item = dbItems.ToDoItem.Where(x => x.Id == id).First();
            dbItems.ToDoItem.Remove(item);
            dbItems.SaveChanges();
            return Redirect("/home");
        }
    }
}

To Do List Application/Views/Home/Create.cshtml
@model domain_entities.ToDoList

@{
    ViewData["Title"] = "Create2";
}

<h1>Create2</h1>

<h4>ToDoList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

To Do List Application/Views/Home/Delete.cshtml
@model domain_entities.ToDoList

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDoList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

To Do List Application/Views/Home/Index.cshtml
@model IEnumerable<domain_entities.ToDoList>

@{
    Layout = "_Layout";
}
<h1>List</h1>

<p>
    <a asp-action="Create">Add new ToDo List</a>
</p>

<p>
    <a asp-action="create" asp-controller="ToDoItems">Add new item</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <h2>
                    <span>@item.Id. </span>
                        @Html.ActionLink(item.Name, "Index", "ToDoItems",
                            new { Name = item.Name }
                        )
                </h2>
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

To Do List Application/Views/Home/View.cshtml
@model To_Do_List_Application.Models.ErrorViewModel

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h4>ErrorViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="View">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RequestId" class="control-label"></label>
                <input asp-for="RequestId" class="form-control" />
                <span asp-validation-for="RequestId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ShowRequestId" /> @Html.DisplayNameFor(model => model.ShowRequestId)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

To Do List Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - To Do List App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">To Do List App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

To Do List Application/Views/ToDo/Create.cshtml
@model domain_entities.ToDoList

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ToDoList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

To Do List Application/Views/ToDo/Create3.cshtml
@{
    Layout = "_Layout";
}
@model domain_entities.ToDoList

<h1>Create Blog Post</h1>

<fieldset>

    <form asp-action="create" asp-controller="todo">

        <div asp-validation-summary="All" class="input-validation-error"></div>
        <p>
            @Html.LabelFor(x => x.Name)
            @Html.EditorFor(x => x.Name)
            @Html.ValidationMessageFor(x => x.Name)
        </p>
        <p>
            <button type="submit">Create post</button>
        </p>
    </form>
</fieldset>

To Do List Application/Views/ToDo/Index.cshtml
@model IEnumerable<domain_entities.ToDoList>

@{
    Layout = "_Layout";
}

<h1>List of TODOLISTS</h1>

<p>
    <a asp-action="Create">Add new ToDo List</a>
</p>

<p>
    <a asp-action="create" asp-controller="ToDoItems">Add new item</a>
</p>

<p>
    Below are a few lists
</p>

<div class="lists">
    @foreach (var list in Model)
    {
        <h2>
            <span>@list.Id. </span>
            @Html.ActionLink(list.Name, "Index", "ToDoItems",
                    new { Name = list.Name }
                )
        </h2>
        <a asp-action="Delete" asp-route-id="@list.Id">Delete     </a>
    }
</div>

To Do List Application/Views/ToDo/List.cshtml
@model IEnumerable<domain_entities.ToDoList>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Add new ToDo List</a>
</p>

<p>
    <a asp-action="create" asp-controller="ToDoItems">Add new item</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <h2>
                    <span>@item.Id. </span>
                        @Html.ActionLink(item.Name, "Index", "ToDoItems",
                            new { Name = item.Name }
                        )
                </h2>
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

To Do List Application/Views/ToDoItems/Create.cshtml
@model domain_entities.ToDoItems

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ToDoItems</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ListName" class="control-label"></label>
                <input asp-for="ListName" class="form-control" />
                <span asp-validation-for="ListName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <p>0 for not Started, 1 for In Progress, 2 for Completed</p>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
                
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="ToDo" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

To Do List Application/Views/ToDoItems/Delete.cshtml
@model domain_entities.ToDoItems

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDoItems</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ListName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ListName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="DeleteConfirm">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="ToDo" asp-action="Index">Back to List</a>
    </form>
</div>

To Do List Application/Views/ToDoItems/Details.cshtml
@model domain_entities.ToDoItems

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ToDoItems</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ListName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ListName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
    *@
</div>

To Do List Application/Views/ToDoItems/Edit.cshtml
@model domain_entities.ToDoItems

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h4>ToDoItems</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ListName" class="control-label"></label>
                <input asp-for="ListName" class="form-control" />
                <span asp-validation-for="ListName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <p>0 for not Started, 1 for In Progress, 2 for Completed</p>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="ToDo" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

To Do List Application/Views/ToDoItems/Index.cshtml
@model IEnumerable<domain_entities.ToDoItems>

@{
    Layout = "_Layout";
}
<h1>
    @foreach (var item in Model)
    {
        @Html.DisplayFor(model => item.ListName)
        break;
    }
</h1>

<p>
    @*<a asp-action="create">Add new item</a>
    @foreach (var item in Model)
    {

        @Html.ActionLink("Add new item", "create", "ToDoItems",
                    new { ListName = item.ListName }
        )
        break;
    }*@
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Content
            </th>
            <th>
                Description
            </th>
            <th>
                CreationDate
            </th>
            <th>
                DueDate
            </th>
            <th>
                Status
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var creationDateShort = item.CreationDate.ToShortDateString();
            var dueDateShort = item.DueDate.ToShortDateString();
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => creationDateShort)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => dueDateShort)
                </td>
                <td>
                    @if (item.Status == 0)
                    {
                        <p>Not Started</p>
                    }
                    @if (item.Status == 1)
                    {
                        <p>In progress</p>
                    }
                    @if (item.Status == 2)
                    {
                        <p>Completed</p>
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit   </a>
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete     </a>
                </td>
            </tr>
        }
    </tbody>
</table>

To Do List Application/Views/ToDoItems/List.cshtml
@model IEnumerable<domain_entities.ToDoItems>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ListName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ListName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>